services:
    massmedia.files_finder_configurator:
        class: Massmedia\FilesFinderBundle\Services\FilesFinderConfigurator
    massmedia.files_finder:
        class: Massmedia\FilesFinderBundle\Services\FilesFinder
        configurator: ['@massmedia.files_finder_configurator', configure]